# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.0.4
_src_path: https://github.com/jupyterlab/extension-template
author_email: akumar@esri.com
author_name: Akshay Kumar
data_format: string
file_extension: ''
has_binder: true
has_settings: false
kind: frontend
labextension_name: jupyterlab_apod
mimetype: ''
mimetype_name: ''
project_short_description: A JupyterLab extension to show NASA pictures in a panel.
python_name: jupyterlab_apod
repository: https://github.com/imdoom/jupyterlab-ext
test: true
viewer_name: ''

